#!/bin/bash

# Mettre à jour le système
echo "Mise à jour du système..."
sudo apt update && sudo apt upgrade -y

# Installer Cockpit
echo "Installation de Cockpit..."
sudo apt install -y cockpit
sudo systemctl enable --now cockpit.socket
echo "Cockpit installé"
echo "Cockpit  : $(systemctl is-active cockpit.socket)"
echo "Cockpit  : https://<adresse_ip>:9090"

