#!/bin/bash

sudo apt-get install -y adduser libfontconfig1 musl
wget https://dl.grafana.com/enterprise/release/grafana-enterprise_9.5.21_arm64.deb
sudo dpkg -i grafana-enterprise_9.5.21_arm64.deb

sudo systemctl daemon-reload
sudo systemctl enable grafana-server
sudo systemctl start grafana-server


echo "Grafana  : $(systemctl is-active grafana-server.service)"
echo "Grafana  : http://<adresse_ip>:3000"
