#!/bin/bash
# Script d'installation d'InfluxDB v1.8 en tant que service pour Raspberry Pi


echo "Mise à jour des paquets..."
sudo apt-get update && apt-get upgrade -y

echo "Téléchargement du paquet InfluxDB v1.8..."
sudo wget https://dl.influxdata.com/influxdb/releases/influxdb-1.8.10_linux_armhf.tar.gz -O influxdb.tar.gz

echo "Extraction des fichiers..."
sudo mkdir -p /opt/influxdb
sudo tar -xzf influxdb.tar.gz -C /opt/influxdb --strip-components=1

echo "Nettoyage des fichiers temporaires..."
sudo rm influxdb.tar.gz

echo "Création de l'utilisateur influxdb..."
sudo useradd -r -s /bin/false influxdb

echo "Attribution des droits à l'utilisateur influxdb..."
sudo chown -R influxdb:influxdb /opt/influxdb

echo "Création du fichier de service systemd pour InfluxDB..."
sudo cat <<EOF >/etc/systemd/system/influxdb.service
[Unit]
Description=InfluxDB Time Series Database
After=network.target

[Service]
User=influxdb
Group=influxdb
ExecStart=/opt/influxdb/influxd
Restart=on-failure
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

echo "Recharge des fichiers de configuration systemd..."
sudo systemctl daemon-reload

echo "Activation et démarrage du service InfluxDB..."
sudo systemctl enable influxdb
sudo systemctl start influxdb

sudo echo "Vérification de l'état du service..."
sudo systemctl status influxdb

echo "Installation terminée. InfluxDB est maintenant installé et exécuté en tant que service."
