#!/bin/bash

# Mettre à jour le système
echo "Mise à jour du système..."
sudo apt update && sudo apt upgrade -y

# install the Mosquitto Broker
sudo apt install -y mosquitto mosquitto-clients

sudo systemctl enable mosquitto.service
